apiVersion: v1
kind: Pod
metadata:
  name: todo-api
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: todo-api
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          cpu: 10m
        limits:
          cpu: 500m
          memory: 250Mi
      volumeMounts:
        - mountPath: /mnt/data
          name: data
  volumes:
    - name: data
      emptyDir: {}
